# Generated by Django 3.1.4 on 2021-01-05 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='uimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img/%y')),
            ],
        ),
        migrations.CreateModel(
            name='userd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('U', 'Urban'), ('R', 'Rural')], default='', max_length=20)),
                ('city', models.CharField(default='', max_length=100)),
                ('occupation', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('B', 'Businessman'), ('D', 'Doctor'), ('E', 'Engineer')], default='', max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=20)),
                ('age', models.IntegerField(blank=True, default='', null=True)),
                ('education', models.CharField(choices=[('M', 'Matriculation'), ('I', 'Intermediate'), ('B', 'Bachelor_Degree'), ('MS', 'Master_Degree')], default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('content', models.TextField(blank=True)),
                ('event', models.CharField(choices=[('S', 'social'), ('R', 'Religious'), ('I', 'islamic')], default='', max_length=20)),
                ('created', models.DateField(default='2021-01-05')),
                ('due_date', models.DateField(default='2021-01-05')),
                ('time', models.TimeField()),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FashionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('fashion_consious', models.CharField(default='', max_length=20)),
                ('brand_consious', models.CharField(default='', max_length=20)),
                ('fav_color', models.CharField(choices=[('B', 'black'), ('R', 'red'), ('W', 'white'), ('G', 'green')], default='', max_length=20)),
                ('fav_dressing_type', models.CharField(choices=[('F', 'formal'), ('C', 'casual'), ('SF', 'semi_formal')], default='', max_length=20)),
                ('fav_design', models.CharField(choices=[('CK', 'check'), ('P', 'plain'), ('L', 'lines')], default='', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
