# Generated by Django 4.2.21 on 2026-06-22 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('master_category', models.CharField(blank=True, max_length=50)),
                ('sub_category', models.CharField(blank=True, max_length=50)),
                ('article_type', models.CharField(blank=True, max_length=100)),
                ('base_colour', models.CharField(blank=True, max_length=50)),
                ('season', models.CharField(blank=True, max_length=20)),
                ('usage', models.CharField(blank=True, max_length=50)),
                ('display_name', models.CharField(blank=True, max_length=300)),
                ('image_filename', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Fashion Item',
                'verbose_name_plural': 'Fashion Items',
            },
        ),
        migrations.CreateModel(
            name='FashionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fashion_choice', models.CharField(db_index=True, max_length=300)),
                ('fashion_tag', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fashion Tag',
                'verbose_name_plural': 'Fashion Tags',
            },
        ),
        migrations.CreateModel(
            name='UserUploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='img/%y')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded Image',
                'verbose_name_plural': 'Uploaded Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('U', 'Urban'), ('R', 'Rural')], default='', max_length=2)),
                ('city', models.CharField(default='', max_length=100)),
                ('occupation', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('B', 'Businessman'), ('D', 'Doctor'), ('E', 'Engineer')], default='', max_length=2)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=2)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('education', models.CharField(choices=[('M', 'Matriculation'), ('I', 'Intermediate'), ('B', 'Bachelor_Degree'), ('MS', 'Master_Degree')], default='', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFashionPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fashion_conscious', models.CharField(default='', max_length=20)),
                ('brand_conscious', models.CharField(default='', max_length=20)),
                ('fav_color', models.CharField(choices=[('B', 'Black'), ('R', 'Red'), ('W', 'White'), ('G', 'Green')], default='', max_length=2)),
                ('fav_dressing_type', models.CharField(choices=[('F', 'Formal'), ('C', 'Casual'), ('SF', 'Semi-Formal')], default='', max_length=3)),
                ('fav_design', models.CharField(choices=[('CK', 'Check'), ('P', 'Plain'), ('L', 'Lines')], default='', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fashion_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fashion Preference',
                'verbose_name_plural': 'Fashion Preferences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextRecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_category', models.CharField(blank=True, max_length=200)),
                ('recommendation_type', models.CharField(choices=[('popularity', 'Popularity Based'), ('user_based', 'User Based'), ('category_based', 'Category Based')], db_index=True, max_length=20)),
                ('recommended_items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Text Recommendation Log',
                'verbose_name_plural': 'Text Recommendation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('dress_category', 'Dress Category'), ('event', 'Event'), ('dress', 'Dress')], db_index=True, max_length=20)),
                ('input_features', models.JSONField(default=list)),
                ('predicted_label', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Text Prediction Log',
                'verbose_name_plural': 'Text Prediction Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TagRecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_input', models.CharField(db_index=True, max_length=100)),
                ('matched_fashion_choices', models.JSONField(default=list)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag Recommendation Log',
                'verbose_name_plural': 'Tag Recommendation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StyleBotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('model_used', models.CharField(default='openai/gpt-4o-mini', max_length=100)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('plan_saved', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylebot_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StyleBot Session',
                'verbose_name_plural': 'StyleBot Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StyleBotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], db_index=True, max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='home.stylebotsession')),
            ],
            options={
                'verbose_name': 'StyleBot Message',
                'verbose_name_plural': 'StyleBot Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageRecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image_id', models.IntegerField()),
                ('recommended_item_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Recommendation Log',
                'verbose_name_plural': 'Image Recommendation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagePredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500)),
                ('predicted_label', models.CharField(db_index=True, max_length=100)),
                ('model_version', models.CharField(default='CNN_v1', max_length=50)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Prediction Log',
                'verbose_name_plural': 'Image Prediction Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_label', models.CharField(db_index=True, max_length=100)),
                ('image_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FashionItemReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('reaction_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fashion Item Reaction',
                'verbose_name_plural': 'Fashion Item Reactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('event', models.CharField(choices=[('S', 'Social'), ('R', 'Religious'), ('I', 'Islamic'), ('P', 'Party'), ('W', 'Wedding'), ('O', 'Office')], default='S', max_length=2)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField()),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='M', max_length=2)),
                ('source', models.CharField(choices=[('manual', 'Manual Form'), ('stylebot', 'StyleBot Chat')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Plan',
                'verbose_name_plural': 'Event Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentSimilarityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=500)),
                ('similar_items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similarity_lookups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Similarity Log',
                'verbose_name_plural': 'Content Similarity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
