# Generated by Django 5.2.1 on 2025-06-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmodel',
            name='created',
            field=models.DateField(default='2025-06-04'),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='due_date',
            field=models.DateField(default='2025-06-04'),
        ),
    ]
